const table = {
    AGGH : [ "HIR","OCE" ],
    AYPY : [ "POM","OCE" ],
    CYEG : [ "YEG","AMR" ],
    CYHZ : [ "YHZ","AMR" ],
    CYMX : [ "YMX","AMR" ],
    CYOW : [ "YOW","AMR" ],
    CYQQ : [ "YQQ","AMR" ],
    CYUL : [ "YUL","AMR" ],
    CYVR : [ "YVR","AMR" ],
    CYWG : [ "YWG","AMR" ],
    CYXS : [ "YXS","AMR" ],
    CYXX : [ "YXX","AMR" ],
    CYXY : [ "YXY","AMR" ],
    CYYC : [ "YYC","AMR" ],
    CYYQ : [ "YYQ","AMR" ],
    CYYY : [ "YYY","AMR" ],
    CYYZ : [ "YYZ","AMR" ],
    CYZF : [ "YZF","AMR" ],
    DTTA : [ "TUN","AFR" ],
    DTTJ : [ "DJE","AFR" ],
    EBBR : [ "BRU","EUR" ],
    EBOS : [ "OST","EUR" ],
    EDDB : [ "SXF","EUR" ],
    EDDE : [ "ERF","EUR" ],
    EDDF : [ "FRA","EUR" ],
    EDDH : [ "HAM","EUR" ],
    EDDK : [ "CGN","EUR" ],
    EDDL : [ "DUS","EUR" ],
    EDDM : [ "MUC","EUR" ],
    EDDN : [ "NUE","EUR" ],
    EDDT : [ "TXL","EUR" ],
    EDFH : [ "HHN","EUR" ],
    EDHI : [ "XFW","EUR" ],
    EFHK : [ "HEL","EUR" ],
    EGBB : [ "BHX","EUR" ],
    EGCC : [ "MAN","EUR" ],
    EGFF : [ "CWL","EUR" ],
    EGHI : [ "SOU","EUR" ],
    EGKK : [ "LGW","EUR" ],
    EGLL : [ "LHR","EUR" ],
    EGPK : [ "PIK","EUR" ],
    EGSS : [ "STN","EUR" ],
    EHAM : [ "AMS","EUR" ],
    EHRD : [ "RTM","EUR" ],
    EIDW : [ "DUB","EUR" ],
    EINN : [ "SNN","EUR" ],
    EKCH : [ "CPH","EUR" ],
    ELLX : [ "LUX","EUR" ],
    ENBO : [ "BOO","EUR" ],
    ENGM : [ "OSL","EUR" ],
    ENZV : [ "SVG","EUR" ],
    EPGD : [ "GDN","EUR" ],
    EPKK : [ "KRK","EUR" ],
    EPKT : [ "KTW","EUR" ],
    EPPO : [ "POZ","EUR" ],
    EPRZ : [ "RZE","EUR" ],
    EPWA : [ "WAW","EUR" ],
    EPWR : [ "WRO","EUR" ],
    ESGG : [ "GOT","EUR" ],
    ESMS : [ "MMX","EUR" ],
    ESSA : [ "ARN","EUR" ],
    FACT : [ "CPT","AFR" ],
    FALE : [ "DUR","AMR" ],
    FAUP : [ "UTN","AFR" ],
    FIMP : [ "MRU","SEA" ],
    GCHI : [ "CHI","EUR" ],
    HAAB : [ "ADD","AFR" ],
    HEAX : [ "ALY","AFR" ],
    HECA : [ "CAI","AFR" ],
    KADW : [ "ADW","AMR" ],
    KAFW : [ "AFW","AMR" ],
    KATL : [ "ATL","AMR" ],
    KAUS : [ "AUS","AMR" ],
    KBDL : [ "BDL","AMR" ],
    KBFI : [ "BFI","AMR" ],
    KBFM : [ "BFM","AMR" ],
    KBGR : [ "BGR","AMR" ],
    KBHM : [ "BHM","AMR" ],
    KBNA : [ "BNA","AMR" ],
    KBOS : [ "BOS","AMR" ],
    KBWI : [ "BWI","AMR" ],
    KCLT : [ "CLT","AMR" ],
    KDEN : [ "DEN","AMR" ],
    KDFW : [ "DFW","AMR" ],
    KDOV : [ "DOV","AMR" ],
    KDTW : [ "DTW","AMR" ],
    KEWR : [ "EWR","AMR" ],
    KGEG : [ "GEG","AMR" ],
    KGFK : [ "GFK","AMR" ],
    KGYR : [ "GYR","AMR" ],
    KIAD : [ "IAD","AMR" ],
    KILG : [ "ILG","AMR" ],
    KIND : [ "IND","AMR" ],
    KJFK : [ "JFK","AMR" ],
    KLAS : [ "LAS","AMR" ],
    KLAX : [ "LAX","AMR" ],
    KLCK : [ "LCK","AMR" ],
    KMCO : [ "MCO","AMR" ],
    KMIA : [ "MIA","AMR" ],
    KMKE : [ "MKE","AMR" ],
    KMOB : [ "MOB","AMR" ],
    KMSP : [ "MSP","AMR" ],
    KMWH : [ "MWH","AMR" ],
    KMZJ : [ "MZJ","AMR" ],
    KOAK : [ "OAK","AMR" ],
    KOKC : [ "OKC","AMR" ],
    KONT : [ "ONT","AMR" ],
    KORD : [ "ORD","AMR" ],
    KPAE : [ "PAE","AMR" ],
    KPDX : [ "PDX","AMR" ],
    KPHL : [ "PHL","AMR" ],
    KPIT : [ "PIT","AMR" ],
    KRFD : [ "RFD","AMR" ],
    KSAN : [ "SAN","AMR" ],
    KSEA : [ "SEA","AMR" ],
    KSFO : [ "SFO","AMR" ],
    KSJC : [ "SJC","AMR" ],
    KSLC : [ "SLC","AMR" ],
    KSTL : [ "STL","AMR" ],
    KSWF : [ "SWF","AMR" ],
    KTPA : [ "TPA","AMR" ],
    KXNA : [ "XNA","AMR" ],
    LBBG : [ "BOJ","EUR" ],
    LBSF : [ "SOF","EUR" ],
    LCLK : [ "LCA","EUR" ],
    LCPH : [ "PFO","MEA" ],
    LEBL : [ "BCN","EUR" ],
    LEMD : [ "MAD","EUR" ],
    LEZG : [ "ZAZ","EUR" ],
    LFBO : [ "TLS","EUR" ],
    LFMN : [ "NCE","EUR" ],
    LFPG : [ "CDG","EUR" ],
    LFPO : [ "ORY","EUR" ],
    LGAV : [ "ATH","EUR" ],
    LGKV : [ "KVA","EUR" ],
    LGRP : [ "RHO","EUR" ],
    LHBP : [ "BUD","EUR" ],
    LIMC : [ "MXP","EUR" ],
    LIME : [ "BGY","EUR" ],
    LIMF : [ "TRN","EUR" ],
    LIML : [ "LIN","EUR" ],
    LIPZ : [ "VCE","EUR" ],
    LIRA : [ "CIA","EUR" ],
    LIRF : [ "FCO","EUR" ],
    LIRN : [ "NAP","EUR" ],
    LJLJ : [ "LJU","EUR" ],
    LKMT : [ "OSR","EUR" ],
    LKPR : [ "PRG","EUR" ],
    LLBG : [ "TLV","MEA" ],
    LOWG : [ "GRZ","EUR" ],
    LOWL : [ "LNZ","EUR" ],
    LOWW : [ "VIE","EUR" ],
    LPPT : [ "LIS","EUR" ],
    LRCK : [ "CND","EUR" ],
    LROP : [ "OTP","EUR" ],
    LSZH : [ "ZRH","EUR" ],
    LTAC : [ "ESB","EUR" ],
    LTAD : [ "ANK","MEA" ],
    LTBA : [ "IST","EUR" ],
    LTBJ : [ "ADB","EUR" ],
    LTBR : [ "YEI","MEA" ],
    LTFJ : [ "SAW","EUR" ],
    LZIB : [ "BTS","EUR" ],
    MGGT : [ "GUA","AMR" ],
    MMGL : [ "GDL","AMR" ],
    NFFN : [ "NAN","OCE" ],
    NTAA : [ "PPT","AMR" ],
    NVVV : [ "VLI","OCE" ],
    NWWW : [ "NOU","OCE" ],
    NZAA : [ "AKL","OCE" ],
    NZCH : [ "CHC","OCE" ],
    OAKB : [ "KBL","SEA" ],
    OBBI : [ "BAH","MEA" ],
    OEDF : [ "DMM","MEA" ],
    OEJN : [ "JED","MEA" ],
    OERK : [ "RUH","MEA" ],
    OERY : [ "XWM","MEA" ],
    OIFM : [ "IFN","MEA" ],
    OIIE : [ "IKA","MEA" ],
    OIII : [ "THR","MEA" ],
    OIMM : [ "MHD","MEA" ],
    OISS : [ "SYZ","MEA" ],
    OIYY : [ "AZD","MEA" ],
    OJAI : [ "AMM","MEA" ],
    OKBK : [ "KWI","MEA" ],
    OLBA : [ "BEY","MEA" ],
    OMAA : [ "AUH","MEA" ],
    OMAL : [ "AAN","MEA" ],
    OMDB : [ "DXB","MEA" ],
    OMDW : [ "DWC","MEA" ],
    OMFJ : [ "FJR","MEA" ],
    OMSJ : [ "SHJ","MEA" ],
    OOMS : [ "MCT","MEA" ],
    OPKC : [ "KHI","MEA" ],
    OPLA : [ "LHE","SEA" ],
    OPNH : [ "WNS","SEA" ],
    OPPS : [ "PEW","SEA" ],
    OPRN : [ "ISB","SEA" ],
    OSDI : [ "DAM","MEA" ],
    OTBD : [ "DOH","MEA" ],
    PABE : [ "BET","AMR" ],
    PACD : [ "CDB","AMR" ],
    PAED : [ "EDF","AMR" ],
    PAEI : [ "EIL","AMR" ],
    PAFA : [ "FAI","AMR" ],
    PAJN : [ "JNU","AMR" ],
    PAKN : [ "AKN","AMR" ],
    PANC : [ "ANC","AMR" ],
    PAPG : [ "PSG","AMR" ],
    PASI : [ "SIT","AMR" ],
    PASY : [ "SYA","AMR" ],
    PAYA : [ "YAK","AMR" ],
    PGSN : [ "SPN","OCE" ],
    PGUA : [ "UAM","OCE" ],
    PGUM : [ "GUM","AMR" ],
    PHKO : [ "KOA","AMR" ],
    PHNL : [ "HNL","AMR" ],
    PHOG : [ "OGG","AMR" ],
    PHTO : [ "ITO","AMR" ],
    PKMJ : [ "MAJ","AMR" ],
    PKWA : [ "KWA","AMR" ],
    PLCH : [ "CXI","AMR" ],
    PMDY : [ "MDY","AMR" ],
    PTRO : [ "ROR","OCE" ],
    PTYA : [ "YAP","OCE" ],
    PWAK : [ "AWK","AMR" ],
    RCKH : [ "KHH","SEA" ],
    RCMQ : [ "RMQ","   " ],
    RCNN : [ "TNN","SEA" ],
    RCSS : [ "TSA","SEA" ],
    RCTP : [ "TPE","SEA" ],
    RJAA : [ "NRT","JPN" ],
    RJAH : [ "IBR","JPN" ],
    RJBB : [ "KIX","JPN" ],
    RJCB : [ "OBO","JPN" ],
    RJCC : [ "CTS","JPN" ],
    RJCH : [ "HKD","JPN" ],
    RJCK : [ "KUH","JPN" ],
    RJCM : [ "MMB","JPN" ],
    RJEC : [ "AKJ","JPN" ],
    RJFF : [ "FUK","JPN" ],
    RJFK : [ "KOJ","JPN" ],
    RJFM : [ "KMI","JPN" ],
    RJFO : [ "OIT","JPN" ],
    RJFR : [ "KKJ","JPN" ],
    RJFS : [ "HSG","JPN" ],
    RJFT : [ "KMJ","JPN" ],
    RJFU : [ "NGS","JPN" ],
    RJGG : [ "NGO","JPN" ],
    RJNK : [ "KMQ","JPN" ],
    RJNS : [ "FSZ","JPN" ],
    RJNT : [ "TOY","JPN" ],
    RJOA : [ "HIJ","JPN" ],
    RJOB : [ "OKJ","JPN" ],
    RJOC : [ "IZO","JPN" ],
    RJOH : [ "YGJ","JPN" ],
    RJOK : [ "KCZ","JPN" ],
    RJOM : [ "MYJ","JPN" ],
    RJOO : [ "ITM","JPN" ],
    RJOT : [ "TAK","JPN" ],
    RJSA : [ "AOJ","JPN" ],
    RJSF : [ "FKS","JPN" ],
    RJSK : [ "AXT","JPN" ],
    RJSN : [ "KIJ","JPN" ],
    RJSS : [ "SDJ","JPN" ],
    RJTT : [ "HND","JPN" ],
    RKJB : [ "MWX","KOR" ],
    RKJJ : [ "KWJ","KOR" ],
    RKJY : [ "RSU","KOR" ],
    RKNN : [ "KAG","KOR" ],
    RKNW : [ "WJU","KOR" ],
    RKNY : [ "YNY","KOR" ],
    RKPC : [ "CJU","KOR" ],
    RKPK : [ "PUS","KOR" ],
    RKPS : [ "HIN","KOR" ],
    RKPU : [ "USN","KOR" ],
    RKSI : [ "ICN","KOR" ],
    RKSM : [ "SSN","KOR" ],
    RKSS : [ "GMP","KOR" ],
    RKTH : [ "KPO","KOR" ],
    RKTN : [ "TAE","KOR" ],
    RKTU : [ "CJJ","KOR" ],
    RKTY : [ "YEC","KOR" ],
    ROAH : [ "OKA","JPN" ],
    RODN : [ "DNA","JPN" ],
    ROIG : [ "ISG","JPN" ],
    RPLB : [ "SFS","SEA" ],
    RPLC : [ "CRK","SEA" ],
    RPLI : [ "LAO","SEA" ],
    RPLL : [ "MNL","SEA" ],
    RPMD : [ "DVO","SEA" ],
    RPVK : [ "KLO","SEA" ],
    RPVM : [ "CEB","SEA" ],
    RPVP : [ "PPS","SEA" ],
    SBBR : [ "BSB","AMR" ],
    SBGL : [ "GIG","AMR" ],
    SBGR : [ "GRU","AMR" ],
    SCDA : [ "IQQ","AMR" ],
    SCEL : [ "SCL","AMR" ],
    SCIE : [ "CCP","AMR" ],
    UAAA : [ "ALA","CIS" ],
    UAAH : [ "BXH","EUR" ],
    UACC : [ "TSE","CIS" ],
    UADD : [ "DMB","EUR" ],
    UAII : [ "CIT","CIS" ],
    UAKK : [ "KGF","EUR" ],
    UATT : [ "AKX","EUR" ],
    UAUU : [ "KSN","EUR" ],
    UBBB : [ "GYD","MEA" ],
    UCFM : [ "FRU","EUR" ],
    UCFO : [ "OSS","EUR" ],
    UEEE : [ "YKS","EUR" ],
    UERR : [ "MJZ","CIS" ],
    UGTB : [ "TBS","EUR" ],
    UHBB : [ "BQS","CIS" ],
    UHHH : [ "KHV","CIS" ],
    UHMA : [ "DYR","EUR" ],
    UHMM : [ "GDX","EUR" ],
    UHPP : [ "PKC","EUR" ],
    UHSS : [ "UUS","CIS" ],
    UHWW : [ "VVO","CIS" ],
    UIAA : [ "HTA","EUR" ],
    UIBB : [ "BTK","EUR" ],
    UIII : [ "IKT","EUR" ],
    UIUU : [ "UUD","EUR" ],
    UKBB : [ "KBP","EUR" ],
    ULAA : [ "ARH","EUR" ],
    ULLI : [ "LED","EUR" ],
    UMMS : [ "MSQ","EUR" ],
    UNAA : [ "ABA","EUR" ],
    UNBB : [ "BAX","EUR" ],
    UNEE : [ "KEJ","EUR" ],
    UNKL : [ "KJA","EUR" ],
    UNNT : [ "OVB","EUR" ],
    UNOO : [ "OMS","EUR" ],
    UNTT : [ "TOF","CIS" ],
    URMM : [ "MRV","EUR" ],
    URSS : [ "AER","EUR" ],
    USCC : [ "CEK","CIS" ],
    USCM : [ "MQF","EUR" ],
    USHH : [ "HMA","EUR" ],
    USNN : [ "NJC","CIS" ],
    USPP : [ "PEE","CIS" ],
    USSS : [ "SVX","EUR" ],
    USTR : [ "TJM","EUR" ],
    UTAA : [ "ASB","EUR" ],
    UTDD : [ "DYU","EUR" ],
    UTDL : [ "LBD","EUR" ],
    UTNU : [ "UGC","EUR" ],
    UTSA : [ "NVI","EUR" ],
    UTSB : [ "BHK","EUR" ],
    UTSS : [ "SKD","EUR" ],
    UTST : [ "TMJ","EUR" ],
    UTTT : [ "TAS","CIS" ],
    UUDD : [ "DME","CIS" ],
    UUEE : [ "SVO","EUR" ],
    UUWW : [ "VKO","EUR" ],
    UUYY : [ "SCW","EUR" ],
    UWGG : [ "GOJ","EUR" ],
    UWKD : [ "KZN","EUR" ],
    UWKS : [ "CSY","EUR" ],
    UWLW : [ "ULY","EUR" ],
    UWOO : [ "REN","EUR" ],
    UWUU : [ "UFA","EUR" ],
    UWWW : [ "KUF","EUR" ],
    VAAH : [ "AMD","SEA" ],
    VABB : [ "BOM","SEA" ],
    VCBI : [ "CMB","SEA" ],
    VDPP : [ "PNH","SEA" ],
    VDSR : [ "REP","SEA" ],
    VECC : [ "CCU","SEA" ],
    VEGT : [ "GAU","SEA" ],
    VGEG : [ "CGP","SEA" ],
    VGHS : [ "DAC","SEA" ],
    VHHH : [ "HKG","SEA" ],
    VIAR : [ "ATQ","SEA" ],
    VIDP : [ "DEL","SEA" ],
    VIJP : [ "JAI","MEA" ],
    VILK : [ "LKO","SEA" ],
    VMMC : [ "MFM","CHN" ],
    VNKT : [ "KTM","SEA" ],
    VOBL : [ "BLR","SEA" ],
    VOHS : [ "HYD","SEA" ],
    VOMM : [ "MAA","SEA" ],
    VTBD : [ "DMK","SEA" ],
    VTBS : [ "BKK","SEA" ],
    VTBU : [ "UTP","SEA" ],
    VTCC : [ "CNX","SEA" ],
    VTCT : [ "CEI","SEA" ],
    VTSG : [ "KBV","SEA" ],
    VTSP : [ "HKT","SEA" ],
    VTSS : [ "HDY","SEA" ],
    VTUU : [ "UBP","SEA" ],
    VVCI : [ "HPH","SEA" ],
    VVCR : [ "CXR","SEA" ],
    VVCT : [ "VCA","SEA" ],
    VVDN : [ "DAD","SEA" ],
    VVNB : [ "HAN","SEA" ],
    VVPB : [ "HUI","SEA" ],
    VVPQ : [ "PQC","SEA" ],
    VVTS : [ "SGN","SEA" ],
    VVVD : [ "VDO","SEA" ],
    VYMD : [ "MDL","SEA" ],
    VYYY : [ "RGN","SEA" ],
    WABB : [ "BIK","SEA" ],
    WADD : [ "DPS","SEA" ],
    WAMM : [ "MDC","SEA" ],
    WARR : [ "SUB","SEA" ],
    WBGB : [ "BTU","SEA" ],
    WBGG : [ "KCH","SEA" ],
    WBKK : [ "BKI","SEA" ],
    WBKL : [ "LBU","SEA" ],
    WBSB : [ "BWN","SEA" ],
    WIDD : [ "BTH","SEA" ],
    WIHH : [ "HLP","SEA" ],
    WIII : [ "CGK","SEA" ],
    WIMM : [ "MES","SEA" ],
    WMKJ : [ "JHB","SEA" ],
    WMKK : [ "KUL","SEA" ],
    WMKP : [ "PEN","SEA" ],
    WSAP : [ "QPG","SEA" ],
    WSSL : [ "XSP","SEA" ],
    WSSS : [ "SIN","SEA" ],
    YBAS : [ "ASP","OCE" ],
    YBBN : [ "BNE","OCE" ],
    YBCG : [ "OOL","OCE" ],
    YBCS : [ "CNS","OCE" ],
    YBMA : [ "ISA","OCE" ],
    YBRK : [ "ROK","OCE" ],
    YBTL : [ "TSV","OCE" ],
    YMML : [ "MEL","OCE" ],
    YPDN : [ "DRW","OCE" ],
    YSCB : [ "CBR","OCE" ],
    YSSY : [ "SYD","OCE" ],
    ZBAA : [ "PEK","CHN" ],
    ZBDT : [ "DAT","CHN" ],
    ZBHH : [ "HET","CHN" ],
    ZBLA : [ "HLD","CHN" ],
    ZBSJ : [ "SJW","CHN" ],
    ZBTJ : [ "TSN","CHN" ],
    ZBYN : [ "TYN","CHN" ],
    ZBYN : [ "TYN","CHN" ],
    ZGDY : [ "DYG","CHN" ],
    ZGGG : [ "CAN","CHN" ],
    ZGHA : [ "CSX","CHN" ],
    ZGKL : [ "KWL","CHN" ],
    ZGNN : [ "NNG","CHN" ],
    ZGSZ : [ "SZX","CHN" ],
    ZHCC : [ "CGO","CHN" ],
    ZHHH : [ "WUH","CHN" ],
    ZHYC : [ "YIH","CHN" ],
    ZJHK : [ "HAK","CHN" ],
    ZJSY : [ "SYX","CHN" ],
    ZLIC : [ "INC","CHN" ],
    ZLLL : [ "LHW","CHN" ],
    ZLXN : [ "XNN","CHN" ],
    ZLXY : [ "XIY","CHN" ],
    ZMCK : [ "UBN","CIS" ],
    ZMUB : [ "ULN","MEA" ],
    ZPLJ : [ "LJG","CHN" ],
    ZPPP : [ "KMG","CHN" ],
    ZSAM : [ "XMN","CHN" ],
    ZSCG : [ "CZX","CHN" ],
    ZSCN : [ "KHN","CHN" ],
    ZSFZ : [ "FOC","CHN" ],
    ZSHC : [ "HGH","CHN" ],
    ZSJN : [ "TNA","CHN" ],
    ZSNB : [ "NGB","CHN" ],
    ZSNJ : [ "NKG","CHN" ],
    ZSOF : [ "HFE","CHN" ],
    ZSPD : [ "PVG","CHN" ],
    ZSQD : [ "TAO","CHN" ],
    ZSQZ : [ "JJN","CHN" ],
    ZSSS : [ "SHA","CHN" ],
    ZSTX : [ "TXN","CHN" ],
    ZSWH : [ "WEH","CHN" ],
    ZSWX : [ "WUX","CHN" ],
    ZSWZ : [ "WNZ","CHN" ],
    ZSXZ : [ "XUZ","CHN" ],
    ZSYN : [ "YNZ","CHN" ],
    ZSYT : [ "YNT","CHN" ],
    ZUCK : [ "CKG","CHN" ],
    ZUGY : [ "KWE","CHN" ],
    ZUUU : [ "CTU","CHN" ],
    ZWSH : [ "KHG","CHN" ],
    ZWWW : [ "URC","CHN" ],
    ZYCC : [ "CGQ","CHN" ],
    ZYHB : [ "HRB","CHN" ],
    ZYMD : [ "MDG","CHN" ],
    ZYQQ : [ "NDG","CHN" ],
    ZYTL : [ "DLC","CHN" ],
    ZYTX : [ "SHE","CHN" ],
    ZYYJ : [ "YNJ","CHN" ] 
};

const toIATA = function(ICAO) {
    return (table[ICAO]? table[ICAO][0] : ICAO);
}
const findRegion = function(ICAO) {
    return table[ICAO][1];
}


const currentDate = function() {
    const KR_TIME_DIFF = 9 * 60 * 60 * 1000;
    const currDate = new Date(Date.now() + KR_TIME_DIFF);

    return (currDate.toISOString().replaceAll('-','').slice(0,8))
}

const ubiRender = function(array) {
    if (!Array.isArray(array)) throw new Error(`${array} is not an Array`)

    const $tbody = document.querySelector('tbody');
        const $fragment = document.createDocumentFragment();
        $tbody.innerHTML = '';

        array.forEach( item => {
            const { fpId, apIcao, apArr, acId, acType, etd, eta } = item;
            const $tr = document.createElement('tr');

            $tr.innerHTML = `<td>${fpId.slice(3)}</td>
            <td>${toIATA(apIcao)}</td>
            <td>${toIATA(apArr)}</td>
            <td>${acId !==null ? acId : ' - ' } / ${acType}</td>
            <td>${currentDate().slice(6,8)}${etd}Z</td>
            <td>${currentDate().slice(6,8)}${eta}Z</td>`;
            $fragment.appendChild($tr);
        });

        $tbody.appendChild($fragment);
}

$('.airline-list').click(function(e){
    $(this).children().removeClass('active')
    $(this).children(`li:contains(${e.target.innerText})`).toggleClass('active');
})

$('.airline-list').click((e) => {
    const airline = e.target.id;
    $.ajax({
        url: "/airline",
        data: { 
            airline: airline,
            date: currentDate()
        },
        method: "GET"
    })
    .done( ({ records }) => {
        records = records.filter(item => item.eta !== null);
        
        this[airline] = records; // 아 진짜 전역객체로 추가하기 너무너무 싫었는데 아 아아아아아
    })
    .done( () => {
        ubiRender(this[airline])
    })
})



const searchAirline = function() {
    const airline = $('.airline-item.active').attr('id');
    if(!airline) return 

    const fltNo = $('input[name="flt-no"]').val();
    const dep = $('input[name="dep"]').val().toUpperCase();
    const arr = $('input[name="arr"]').val().toUpperCase();

    let searchResult = this[airline];

    searchResult = fltNo? searchResult.filter( record => record.fpId.slice(3) === fltNo ) : searchResult
    searchResult = dep? searchResult.filter( record => toIATA(record.apIcao) === dep ) : searchResult
    searchResult = arr? searchResult.filter( record => toIATA(record.apArr) === arr ) : searchResult
    console.log(searchResult)
    ubiRender(searchResult);
}

$('.sked-search')
.on("keyup", e => {
    if (e.keyCode === 13) searchAirline()
})
.on("click", e => {
    if (e.target === document.querySelector('.sked-search i')) searchAirline()
})


// etd kst로 나와있는거 바꾸기
// 
function kstToUtc(str) {
    const array = Array.from(str);
    array.splice(4,0,'/');
    array.splice(7,0,'/');
    array.splice(10,0,' ');
    array.splice(13,0,':');
    const formattedStr = array.join('');

    const utcTime = new Date(Date.parse(formattedStr));
    return `${utcTime.getUTCDate()}${utcTime.getUTCHours()}${utcTime.getUTCMinutes()}`
    // return utcTime.toISOString().slice(8,16).replace('T','').replace(':','');
}